import Navbar from "@/components/custom/Navbar";
import { ThemeProvider } from "@/provider/ThemeProvider";
import type { Metadata } from "next";
import { Rubik_Doodle_Shadow } from "next/font/google";
import "./globals.css";

export const Primary_Font = Rubik_Doodle_Shadow({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar font={Primary_Font} />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
